---
name: "Auto Labeler"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  auto_labeler:
    permissions:
      contents: read
      pull-requests: write
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/auto-labeler.yaml@51be22c58e3d4b33b4fbdc1dcf257c481695ce36 # v0.7.0
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
